# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6fd84416c96bbfc5804ba02c014a1a6436ea70bbea56e7e89db303a0ba5c4934ad282574d8efdc177155358fa561b4767c6c5a77ea970d186537834a612d00f

test:
  secret_key_base: a6a3b96b5604028cf0820afa27e25e527024ead39219cc07439c011d93e401b09fe73a50863ee9bdaf2051b8ff42baab2cc6d674d9c66822001cb957f44239b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
